# docker-compose.yml

services:
  web:
    image: ghcr.io/lukashirsch99/swimresults:0.2
    ports:
      - 8080:8080
    secrets:
      - db-password

    environment:
      # Container-Name of database container
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=admin
      - POSTGRES_DB=swim-results
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    expose:
      - 5432
    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: swim-results
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password

    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
