# docker-compose.yml

services:

  web:
    image: lukashirsch99/swim-results:0.1
    ports:
      - 8080:8080

    environment:
      # Container-Name of database container
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=swim-results
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always

    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: swim-results
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    expose:
      - 5432

    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  db-data:
