name: swim_results
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-27.0.dev <4.0.0'

dependencies:
  custom_line_indicator_bottom_navbar: ^0.0.8
  firebase_messaging: ^14.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  rive: ^0.12.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.22
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
