// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: start.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateStartsParams struct {
	Heatid    int32
	Swimmerid int32
	Lane      int32
	Time      pgtype.Time
}

const getStartCntForEvent = `-- name: GetStartCntForEvent :one
SELECT count(*) FROM start
JOIN heat on heat.id = start.heatid
WHERE heat.eventid = $1
`

func (q *Queries) GetStartCntForEvent(ctx context.Context, eventid int32) (int64, error) {
	row := q.db.QueryRow(ctx, getStartCntForEvent, eventid)
	var count int64
	err := row.Scan(&count)
	return count, err
}
