name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: cd backend && go get .

      - name: Log into Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/swimresults:latest
            ghcr.io/${{ github.actor }}/swimresults:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker stack deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: swimresults
          file: docker-stack.yml
          host: 140.238.219.59
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
